spring:
  application:
    name: my-secret-api
  datasource:
    url: jdbc:postgresql://localhost:5432/my_secret_db
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs

server:
  port: 8080